spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: dropbeeseller@gmail.com
    password: B33S3ll3r@12345
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    test-connection: false

  datasource:
    username: admin
    password: 123456789.*dhl
    url: jdbc:mysql://database-develop.c9ir9n4tc2qb.us-east-2.rds.amazonaws.com:3306/pepegangadb
    #url: jdbc:mysql://database-prod.c9ir9n4tc2qb.us-east-2.rds.amazonaws.com:3306/pepegangadb
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      hibernate:
        SQL: debug



