server:
  port: ${PORT:0}

spring:
  application:
    name: user-service
  profiles:
    active: @spring.profiles.active@
  mail:
    host: smtp.gmail.com
    port: 587
    username: dropbeeseller@gmail.com
    password: B33S3ll3r@12345
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    test-connection: true
