server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
spring:
  application:
    name: meli-service
  profiles:
    active: @spring.profiles.active@